#!/bin/sh

BIT_DAEMON=/usr/local/sbin/ban-internet-trollsd
BIT_DAEMON_NAME=${BIT_DAEMON##*/}
BIT_PIDFILE=/var/run/bit.pid

. /lib/lsb/init-functions

getpid() {
    #local pid=`pgrep -f $BIT_DAEMON_NAME`
    local pid=`pgrep -f $BIT_DAEMON`

    if [ "x$pid" = "x" ]; then
        pid=0
    fi

    return $pid
}

daemon_up() {
    getpid
    local pid=$?
    local retval=1

    if [ $pid -gt 0 ]; then
        retval=0
    fi

    return $retval
}

bit_start() {
    local rc=1

    #if start-stop-daemon --start --quiet --background --pidfile $BIT_PIDFILE --make-pidfile --exec $BIT_DAEMON -- --no-detach --daemon
    if daemon_up; then
        log_daemon_msg "Already running" "$BIT_DAEMON_NAME"
        rc=255
    else
        log_daemon_msg "Starting bit daemon" "$BIT_DAEMON_NAME"
        if start-stop-daemon --start --quiet --background --pidfile $BIT_PIDFILE --make-pidfile --exec $BIT_DAEMON; then
            sleep 1

            if daemon_up; then
                rc=0
            fi
        fi
    fi

    if [ $rc -eq 1 ]; then
        log_failure_msg "bit daemon failed to start"
        rm -f $BIT_PIDFILE
    fi

    log_end_msg $rc
}

bit_stop() {
    local rc

    if daemon_up; then
        log_daemon_msg "Stopping bit daemon" "$BIT_DAEMON_NAME"
        start-stop-daemon --stop --quiet --oknodo --pidfile $BIT_PIDFILE
        rc=$?
        rm -f $BIT_PIDFILE
    else
        log_daemon_msg "Not running" "$BIT_DAEMON_NAME"
        rc=255
    fi

    log_end_msg $rc
}

bit_reload() {
    local rc
    if daemon_up; then
        getpid
        local pid=$?

        log_daemon_msg "Reloading" "$BIT_DAEMON_NAME"
        kill -HUP $pid
        rc=$?
    else
        log_daemon_msg "Not running" "$BIT_DAEMON_NAME"
        rc=255
    fi

    log_end_msg $rc
}

bit_status() {
    if daemon_up; then
        getpid
        local pid=$?

        if [ ! -f $BIT_PIDFILE ]; then
            echo $pid > $BIT_PIDFILE
        fi

        local pidf=`cat $BIT_PIDFILE`

        if [ $pid -ne $pidf ]; then
            echo $pid > $BIT_PIDFILE
        fi
    else
        rm -f $BIT_PIDFILE
    fi

    status_of_proc -p $BIT_PIDFILE "$BIT_DAEMON" $BIT_DAEMON_NAME
}

case "$1" in
    start)
        bit_start
    ;;
    stop)
        bit_stop
    ;;
    restart)
        bit_stop
        bit_start
    ;;
    reload)
        bit_reload
    ;;
    status)
        bit_status
    ;;
    *)
        echo "Usage: /etc/init.d/bit {start|stop|restart|reload|status}"
        exit 1
esac

exit 0
