#!/bin/sh

BANIT_DAEMON=/usr/local/sbin/banitd
BANIT_DAEMON_NAME=${BANIT_DAEMON##*/}
BANIT_PIDFILE=/var/run/banit.pid

. /lib/lsb/init-functions

getpid() {
    #local pid=`pgrep -f $BANIT_DAEMON_NAME`
    local pid=`pgrep -f $BANIT_DAEMON`

    if [ "x$pid" = "x" ]; then
        pid=0
    fi

    return $pid
}

daemon_up() {
    getpid
    local pid=$?
    local retval=1

    if [ $pid -gt 0 ]; then
        retval=0
    fi

    return $retval
}

banit_start() {
    local rc=1

    #if start-stop-daemon --start --quiet --background --pidfile $BANIT_PIDFILE --make-pidfile --exec $BANIT_DAEMON -- --no-detach --daemon
    if daemon_up; then
        log_daemon_msg "Already running" "$BANIT_DAEMON_NAME"
        rc=255
    else
        log_daemon_msg "Starting banit daemon" "$BANIT_DAEMON_NAME"
        if start-stop-daemon --start --quiet --background --pidfile $BANIT_PIDFILE --make-pidfile --exec $BANIT_DAEMON; then
            sleep 1

            if daemon_up; then
                rc=0
            fi
        fi
    fi

    if [ $rc -eq 1 ]; then
        log_failure_msg "banit daemon failed to start"
        rm -f $BANIT_PIDFILE
    fi

    log_end_msg $rc
}

banit_stop() {
    local rc

    if daemon_up; then
        log_daemon_msg "Stopping banit daemon" "$BANIT_DAEMON_NAME"
        start-stop-daemon --stop --quiet --oknodo --pidfile $BANIT_PIDFILE
        rc=$?
        rm -f $BANIT_PIDFILE
    else
        log_daemon_msg "Not running" "$BANIT_DAEMON_NAME"
        rc=255
    fi

    log_end_msg $rc
}

banit_reload() {
    local rc
    if daemon_up; then
        getpid
        local pid=$?

        log_daemon_msg "Reloading" "$BANIT_DAEMON_NAME"
        kill -HUP $pid
        rc=$?
    else
        log_daemon_msg "Not running" "$BANIT_DAEMON_NAME"
        rc=255
    fi

    log_end_msg $rc
}

banit_status() {
    if daemon_up; then
        getpid
        local pid=$?

        if [ ! -f $BANIT_PIDFILE ]; then
            echo $pid > $BANIT_PIDFILE
        fi

        local pidf=`cat $BANIT_PIDFILE`

        if [ $pid -ne $pidf ]; then
            echo $pid > $BANIT_PIDFILE
        fi
    else
        rm -f $BANIT_PIDFILE
    fi

    status_of_proc -p $BANIT_PIDFILE "$BANIT_DAEMON" $BANIT_DAEMON_NAME
}

banit_debug() {
    if daemon_up; then
        getpid
        local pid=$?

        case "$1" in
            0) sig=10; echo -n "Turning debug ON.. "  ;; # USR1
            1) sig=12; echo -n "Turning debug OFF.. " ;; # USR2
        esac

        kill -$sig $pid
        r=$?

        if [ $r -eq 0 ]; then
            echo "Done"
        else
            echo "Failed"
        fi
    else
        status_of_proc -p $BANIT_PIDFILE "$BANIT_DAEMON" $BANIT_DAEMON_NAME
    fi
}

case "$1" in
    start)
        banit_start
    ;;
    stop)
        banit_stop
    ;;
    restart)
        banit_stop
        banit_start
    ;;
    reload)
        banit_reload
    ;;
    status)
        banit_status
    ;;
    debugon)
        banit_debug 0
    ;;
    debugoff)
        banit_debug 1
    ;;
    *)
        echo "Usage: /etc/init.d/banit {start|stop|restart|reload|status|debugon|debugoff}"
        exit 1
esac

exit 0
